---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: transac-agg-api-secret
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgApXiNh6b27z8pIdwl7KapWUyyg6PK4pOYs7PNyUlvpJjlt9ckwfM9FiR9uCC/XQmZgK+I9+PE3YQccn5LXXUXBGOLNVvd5OAfCjQRnCCwpA3aP+CLdmGCvOM2tJnbEjqAoyHE/7Y5LedK5jGhtMM0oMkeCm94vxUg99OzJcRIwRMxHxpoA1G3IbSvqWtpyfdRlffUmZUwD7meeAes5o8L8MZg9h62C/oPrTqkbvsoCBa0OuUPxrxCRk7J25X89OweFyyLYPl+KxqAMq5jkdkvbcpC52OMj+rHDYgGCHFYTNoLR3fVOy3c8fj6/F+vyBcI6/wyjLwlr7WcYlkVET9LKS08OlIDDBCGI4DesNQ8WukxkBPb04qLNDIubkpZvNuFQtBsSRM39j9s9QGvjnAQPaYsylSASyyeA5kJ77T+S/vW6VWl2GbXnHKE3lQH9qJ4biPZV+Z0AMYa7biq+/qQubf8cExH542cTLRhbw5i8vDGWH5v5tfVUTg0LNmRhtzJ6okVCTNo4VaVG1BUetsfq3aKLIGZ+MCH4R9NU2ZtOsfjQugddHtLr5bV3DTSSytNMqdmnhRNZspXMx9M0tMiIWGWm0EdPw0qOPregFo1CJL5sxukTvf/BrvQwTCsI/lngA9reYQKmJY6zOesrdAwNva8GrhXZ8o5vXsZhkQJl1r7oL5G13CzPSQgBNMHJJhoKb7SA7tMd2gSIgjg=
  template:
    metadata:
      name: transac-agg-api-secret
      namespace: dev
