---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: transac-agg-api-secret
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgBC48g9mEmvOBIKcma8AgEl++blVqjUlNCiDr4UE4gb1vXgzcLRjncoExXHfP5HsqCmrOJd59OpRFR2C5QQdWEQRbXdNC6OSlCnAvcaqeeAHyuB5sTC3CWq8D1HO4MtAChe/dUTlF0JcYevRd+c1Kf/D+0f1ZzddyMpcf3NTfQRgx3SMPvj+YBENpIMGuAYT1+T0WYq/l+euugaeD7VZTerT1s6msZ4bnYPijqaT0V2DMAvH7gPXff5JpjFwxMQ5VqwnNncC2WXFoQCvNjuq5nsmUULT2jQKzGb1lbX1b1aIaInsVsUV655Qj92PVEjFkjYOcSbOthHn6jhSkRg3XdcUFH/3P/9hll3CL10jB2Fkb/mQFfjVXPSwmcfVLv2nY+HVRSIdrXcbHpQnvUjjoRMrtaXqNboP/Z1ABY3kI30W01Mx4URiHx2pM/PP2zl7Nh+KmhcN1ftD3fJYgEaQhAIMet9VElWPiUKaJnXBhAdmyVXTSXj8fB1zFLu60SeIwTdCt+pXGqRCbpUCYPSvrs0I0YNnVyDIp/gaspPgm2aYsQNJCjDEhuP3C0h80e5QdsfPtiedFK139Ggz8zCTPBXUy10Es91YaWPgbJt82Wgy5K6lBUwN47okM4kDV6/+c684mP91CzuDlMY5O2T+z9ktetFxGJ1truiSeaiX+1sMg6LBGnetgEU9xRLanLGuFFd7dFa33EmnIe2x4o=
  template:
    metadata:
      name: transac-agg-api-secret
      namespace: dev
