---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: transac-agg-api-secret
  namespace: dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgDMgUpa6vP/RtarXQVGd1KfgBAPCn3din7e9Me7Nz+jlKYvPOegTIY9S4GIKk+K34VzorvNV+0tAkFSJ6J7ch+NwsyQ+wQl+GaZQq1q3I+dRUR7FAJyddS2qaxm5/G82OHXvVtDznd9Wl/SIfSd1KKDk2q7e5Rwn63CMQxffPnL/PmX61RoIUvY96sqIMauA+UFsxIypV7CtQfhroI3PIwcuWxD2whoD9Zk/jHHxWd2ixJiu1TTgGHisU3wLvQFq+Pw1lGtiV/6evtxEfbXa3Ue4622xfdyAV5wkIj9a1pzqFgcJi89bIx0/bfKlmc5c7zETtcuhXteu62GLp9YdHyy+5eNr57JmAOtj2V+mwYc6sCHI8gKFYTvjVga+LJ9015ez5iUcaz/C9vCos3Ehc/XhMoP3EsQ1yRxDgDvznDTuz+1rkF73xTrxzrLuCnx41kPwZlX77Gv1Oukmi+Qay2OvS5DBYkGB+QXVzPbmOmuRryhNuuxImkuSOboG4CK8fwVzmUYMBQ0X1ZU6dngvgyhX6s6LmysMV9I+6GjHIy1w+d2idqu1t1A5KnY3YehXWKxap3ryB5oYXN8Rmxsbds3zHH5m8QUWJuyJME18NclWRSaTf7nSCzAL9koILu7qVR9+DJDeRI2uBvnU8GuKYQx0kY9+0JK/Wu/5mNnt1vGP3dGXWuW2Fo7kS9ozIstBUjYwAlaDMYebQ==
  template:
    metadata:
      name: transac-agg-api-secret
      namespace: dev
