---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: transac-agg-api-secret
  namespace: dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB1RVM6+16LG67HPAMmoma9IPkKMnst4uFFKSNI0fYoRwJd546RZxmbYWzJsIFjTTtoLM8SokhjFF5OXafrCN7PxsvbGWkaRykwFMdQCSq4BRncjPwXFScsQUV1i3j2mGC2obE49KbuVmWoIaNRjyr8IGmeOsQXr3JInKq4z9zdFYlxnGvYr+L4wOySj89yZGT1rLJ+ovnQ3aKCt8rWvzmZI2VIcPq4LrBVn7DjWzCr8cUJB69OBgcRWDom3JFKjRD20n8WeguJfwM9kEXvvHluMxQQXriMlFm55SdB33lmzn2/YT26sYsrMV2cnd/Ns6r8yfbe0qvnESYl8HIds/DnCDnizkM116JYo4pZmjutNn/46SqVFBehAEYzNZrsQOIpgR70ndRCFeHCNTi/Uv+fvsxTNo0hrCa8lvtzEidclpvuM0ahWxaFKLBtq9yABbVyX/YjK6wN8Kf9rYe+K0gvTNPRB0TLGbueGNugMLnOIA0mzY7EEAYCwNhBvpBqM67p2Rsbgucmxk24jWAps4PFxqT4DQtEL8Vn7LwIbmS+9kzJW9wEX3nuHHndIi7kydHljjgrmhKtlfEdbgk+pDfNSyiVktUSHdrub8bvZ+Dy2dfruMco5+VHryS5c6NWFT3hp8CzSdXSwI8B6gLFX/jEmt0N8yYMZbNEBWkZuiFzezKBXvzzsNWHZxYtnipzDYRo2P5MHMsllZK2v1Y=
  template:
    metadata:
      name: transac-agg-api-secret
      namespace: dev
