---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: transac-agg-api-secret
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgAYwE7iNV7Qn1XrcsGX2UzGwtjx095U6Bz/17ojkmcJTI6Cf0B25DnrpP048PZSGYtUdAZlIXYrhWREGpMx6NQAjBBDmttkiHJsorWKoSYlOtWWY0lLH1aEvi3dq9xEA7+PhjKoyAUlnApORCMEbUnRfQQHTSHGQjbcnfqq7cz601oWsA6Fk6nDtLs5tsrMfzI37yaBo3rvT7wqhhjefSQbwh8U5CYf+V7exasUUtLEDBtNd0FVDI5fNvY0kaVAu3lhcHKYi84jQoG+Iw+wrNxLeUGHRrMiNhGp3AVxr0iaZawmVwtgUXj9LsiHLNQPaq7ra4SNmBOGy/RZrgxVkvy8HuP/iGFkp5OXrJZo1YPz+Reu0EvgCwIH2BCZI2aI80Hgy2nieV/kn6qKAVWojdxWPZ9ZNdp/8/8MkSBfJTDRs8yn4OujgmLp/MwQ2eX2px7wMx+xgCTjwgAghEijtAkpQlnjwxVGyaKtsYcQwgq+zAJZMv/HaOQt+3RXr1A1Doac0z8S65TJkezg/gwm2FkgThlnooKmz0CKPHQnx+Rcm4+b8xhCDfsIpr7Y9EIrLTvs146It4oJDXQwuP1vTRmb9C/kgdC3/yMG3orOSAs0UGbA8MRDYUgcD34CG2LyXkNfTq1pmYbNZvCs3UigX4ftOQgd7c4TqVDpH3oAKhXS5dk+5zN7fAxPwRD2GCED3XkuY9c1jjbWDm0e1Cs=
  template:
    metadata:
      name: transac-agg-api-secret
      namespace: dev
