---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCHB74JEEdjvzLzJNxVzVIlbkZmTYu20FJieD/HA/bdHkMgT1JGwkviPIM/sFikbgbaREvpBeqiSZMw9BID079TeEfx/M/aPwxJcRUmp5qDKBmdRDy7dXRptpCt79JrAMNUsBiKD+18eXFqq8Bc51QLtwKjvmGGqRScU723dhORH8BVglaRCMEDql8Nq4itbj0VpNlW2te+ZelkpOd313RqQj2qy8HWjdWdbUmUHdZSzIumxlQfXQSlONp+DI98/fCWAf/hivTNRhCviYWYt201ZrWrKjMsq+wDzWjtlvzwJWG3joqegOnPFNgzuUoDPyyQEyh/SkrwejZpvmnE4erbYiox/q8u7DobpI2U6KMSBEh18VrHk/poBtxOVgWGvdAy/W/0njNxwwNe5AULui4vIsc4Y4K/6KNFPcxPWRruZwTJm5PJSkIv1Al9uIwc/cdtX9HxnXH4Icfq3myElAg7fu6PpGpAVDc7HGeOdzTKQO0fhpfetm0VS+XNZMFhsXqVuwqrfcq643nM9x8XzzjW2et2tH02+wiNt5eG+4CZfPcRB7OULJOpex3avTsZ4ZvR4LYYE13aPXz5E4R9ZQK8l7BJNv26qwKi8olsQK7LSvt3fmQ+oeCpFatW8yCID+9yoNzqFhGt24A2NjJYZHDRBoJeWnuB6oPH4Fk61o9iVWspT1QYxDy8ZuQkuuYTHxKWJZrKeTSwdQ==
  template:
    metadata:
      name: postgres-secret
      namespace: dev
