---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: transac-agg-api-secret
  namespace: dev
spec:
  encryptedData:
    grafana-admin-password: AgBjfv1N7ig6KjQ1FqRrCjxXHYEHKGGNI2SuHgceuQm6lD0snRVB4SX0PiBpmVq4ba39ZkNnSsc2/LR0mgbHrc+R9FnBf7ZYIQA7kphvtOFBkDO9ypjqdGISR4H/wrjExMXljpDHictJXjWuRgbCj3R2vkDCzLB3XZ6DTCWNGaWEo1tujjwVXDYjS/sPkGPtxa4u0mdsJjwuZLGyacBsvgWdiU4wulq8sWNjo4zEyejiwK9vqvEMlZk7HzPIj/TX0SbRCEi0UZSLl0cognEjXyA3usDCtG4d2r5tfTkCvsJOimlq4mnQWuu+whQVTk6m86WVZC8HKCU71UCRz4B+FznAG1oR3oTpw9Annt8NaiE1NNKLt9Mb7X2vzMe9fyiDJs3GFC8SyIAazd/+tjIHeRroostF7L1Bv1jjt4Oq7t9QCKvMIPJiD5qqUZhzvn/8/UA1DkWGRSOGV7m0TITOWcJeXlGCZr3VGeF2ADEPIxD//8RNBWhoT9tKz+TZbU7Ef5L7MaJHxWf4/T1xd+gPmlE4/CrmaLc/s1iw3zIw59JnWOBfvn68VXiHVpOvMUDQ7IMw/jSSLNatiLgdxFQiYcm7+MPYmzIf04rOwKikHXBI4WpCC/SVRGNmkwpN4lWgK96txZPcHpy1aUtXCN2Z6pTBffOHrMIXMEVixiq9pVLwwtZ8v0bd1eouT1PNpSTIw7hTVz1Tug==
  template:
    metadata:
      name: transac-agg-api-secret
      namespace: dev
