---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: dev
spec:
  encryptedData:
    grafana-admin-password: AgCah4+8UJr/yxteIR7KTLYzR9a94Wu5q7dus9OtVXFnyLM2ke+5ysfKP10LShwLw/EdJGcWc3oQ9qhrW+09HEfNzlcr8Ff1r0UZPI5OYcOdBSMpV+c3qSDBKO2GGtcQ73pQlRt01UqaDC+eaeF2XKM10cvrTRkBHczlpYVU1cmkoBEBIWolhA3nBvx2ku1SnkBD+VmPdEPmApVgrOo3LZJeuMRtzTyNqYuSajhFV3ZgP5ypYl58YEUoMJc1ME883cbTHvZkDY4L14j0HE+7eLTBXogzBM3KiBhWXB6Z4ahFLL25vgRinyOdBnkHbzZPt7Er6uSqgBjeO0cUp7wfprlD/HmtstXzAwVrKQofOupYamUFjJctGbM14zmWJMU7ZyL25fysiLtajYQNMMhtbxboIxeNCLNNRaRoHWeNJY56jLpzi9YPQj+reB+ve8UKXgLNmkvd2SGzEypCckUUWygSa+LXEbXA9pkDvIHwwfbUoANABEHjqEFBi12N5BkkdsvWV48q3/EBEKtJfl9SD0yQCusbEwJcqoWsSTMmrMl8JIXofJZLbdRFx9NBqhu1LK4Ql/NtJuXYsg3qNiTzfXfBzdsHSTv9FqfdoJ+F3QTSGHn9Vuh5XoX/xgtSd1hBVuXvamBsjQiKjNy6oTku4tkxDJ4lbpRCqhw4sbW3pIpW3E8j8X0rhoers5KCgpQmlZppk/TbK33EeSm2N0SP5S1Ngg==
  template:
    metadata:
      name: grafana-secret
      namespace: dev
