---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: dev
spec:
  encryptedData:
    grafana-admin-password: AgAVyaP4Oa3IvMdlmGsioIvyi6WnkL7l5zyHcfNfCGxjZQxPvgx3OD/8v6YaxRukx8a4SjY9wBFjNIxwiHcc4M/PPw3Uj+qYvLEd2K8INynxpy80i7mDZIrcYFaCZG89Z8sHz4rGXsL2EAFC5h51ZxDVM6S9KRR+R8kWfkPPh4ecYvXxuJExUN1eAPdZ9TELuXRR/WMoB4KuYE5LvcFWAIcEr46WoRl04Fs8z7tvGkoCUN9/z+aFRmQerlT5AyB2V9vPGdZH/mvMOp827s/VvqgE++RYPsYxNKijvXNax/T9Lyy+fU4PZzFIQA1lWZw2BJXD6CbLTThpararsL/nkMLpOu2EieT86K+1zVve7WKEKk661apmu41xCpmVDtllPXbsJ+W5g9M+E05jGgKBqHaq9yJikj3C+O+VI2Xich7vkqkWXM4OGuXHEUtf7nOJtjntlEOUhaMLNtvTdmAbIlktR/uzJq6YH5aUF2S0dNioWLEgHs8wMqXOqzpcEXgQNFREnN3s6X82MWY5v7vu0fUc7ND4komZvlGXZp116fnAHHvlre/xf5VZr4ZlBriVfUVM6WRzcVOfPmkFI/agkZsZEUMo1kVGhD5yVu0EL9MRdbCrMcjyPhKVStYI09QQk40HLA7Gf8bNDL/qU6gxAIBDmNzlVUMyQrFHY1rcIdMswq2T5cacsTRl2M8acDSLw5DbyxwhZudgVj4NWS0NKtWlhA==
  template:
    metadata:
      name: grafana-secret
      namespace: dev
