server:
  replicaCount: 1
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 500Mi
  frontend:
    readinessProbe:
      tcpSocket:
        port: rpc
      initialDelaySeconds: 30
      periodSeconds: 10
      failureThreshold: 3
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
  history:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
  matching:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
  worker:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop:
          - ALL
  config:
    clusterMetadata:
      enableGlobalNamespace: false
      failoverVersionIncrement: 10
      masterClusterName: "active"
      currentClusterName: "active"
      clusterInformation:
        active:
          enabled: true
          initialFailoverVersion: 1
          rpcName: "temporal-frontend"
          rpcAddress: "temporal-frontend.dev.svc.cluster.local:7233"
          httpAddress: "temporal-frontend.dev.svc.cluster.local:7243"
    publicClient:
      hostPort: "temporal-frontend.dev.svc.cluster.local:7233"
    persistence:
      numHistoryShards: 1
      datastores:
        default:
          sql:
            createDatabase: true
            manageSchema: true
            pluginName: postgres12
            driverName: postgres12
            databaseName: temporal
            connectAddr: "postgres.dev.svc.cluster.local:5432"
            connectProtocol: "tcp"
            user: postgres
            existingSecret: transac-agg-api-secret
            secretKey: POSTGRES_PASSWORD  # kics-scan ignore-line
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: "1h"
        visibility:
          sql:
            createDatabase: true
            manageSchema: true
            pluginName: postgres12
            driverName: postgres12
            databaseName: temporal_visibility
            connectAddr: "postgres.dev.svc.cluster.local:5432"
            connectProtocol: "tcp"
            user: postgres
            existingSecret: transac-agg-api-secret
            secretKey: POSTGRES_PASSWORD  # kics-scan ignore-line
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: "1h"

web:
  replicaCount: 1
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: NodePort
    port: 8080
    nodePort: 30081
  additionalEnv:
    - name: TEMPORAL_CORS_ORIGINS
      value: http://localhost:3000

admintools:
  enabled: false

shims:
  dockerize: false
  elasticsearchTool: false
