server:
  image:
    repository: temporalio/server
    tag: 1.31.0
  config:
    persistence:
      defaultStore: default
      visibilityStore: visibility
      numHistoryShards: 512
      datastores:
        default:
          sql:
            createDatabase: true
            manageSchema: true
            pluginName: postgres12
            driverName: postgres12
            databaseName: temporal
            connectAddr: "postgres.dev.svc.cluster.local:5432"
            connectProtocol: "tcp"
            user: postgres
            existingSecret: transac-agg-api-secret
            secretKey: POSTGRES_PASSWORD
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: "1h"
        visibility:
          sql:
            createDatabase: true
            manageSchema: true
            pluginName: postgres12
            driverName: postgres12
            databaseName: temporal_visibility
            connectAddr: "postgres.dev.svc.cluster.local:5432"
            connectProtocol: "tcp"
            user: postgres
            existingSecret: transac-agg-api-secret
            secretKey: POSTGRES_PASSWORD
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: "1h"

web:
  enabled: true
  image:
    repository: temporalio/ui
    tag: 2.49.1

admintools:
  enabled: false

schema:
  useHelmHooks: true

shims:
  dockerize: false
  elasticsearchTool: false
